name: note_x
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  easy_localization: ^3.0.7
#  firebase_core: ^3.5.0
#  cloud_firestore: ^5.4.2
#  firebase_auth: ^5.1.4
#  firebase_storage: ^12.3.1
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/main_image/

  fonts:
     - family: Cairo
       fonts:
         - asset: assets/fonts/Cairo-font.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
